project:
  type: website

website:
  title: "personal-website1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd 
        text: About 
      - href: projects.qmd
        text: Projects
      - href: courses.qmd
        text: Courses
  
  
  page-footer: 
    right: "&copy; 2025, Kimberly Cui"
    
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



